TUTORIAL 5

In [5]:
import numpy as np
import pandas as pd

In [6]:
#playing with data frame
df= pd.DataFrame(np.arange(0,20).reshape(5,4), index = ["Row1", "Row2", "Row3", "Row4", "Row5"] , columns = ["Column1", "Column2", "Column3", "Column4"])
df.head()

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [7]:
#file saved with comma separation = CSV comma separated value
df.to_csv('TEST1.csv')

In [3]:
#Accessing the elements
## there are 2 ways to do that
### 1. .loc , 2. .iloc (loc as in location and i is for index
#if no row & column both >1 its a data frame but if even a row or column =1
#it is DATA SERIES & not DATA FRAME .

In [8]:
df.loc["Row1"]

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [9]:
type(df.loc["Row1"]) #output says that it is a series since only one row has been chosen

pandas.core.series.Series

In [10]:
df.iloc[0:2 , 1:3]

      Column2  Column3
Row1        1        2
Row2        5        6

In [11]:
df.iloc[0:3 , 2:4]

      Column3  Column4
Row1        2        3
Row2        6        7
Row3       10       11

In [12]:
df["Column1"].unique()

array([ 0,  4,  8, 12, 16])

In [13]:
df.iloc[0:3 , 2:4].values.shape

(3, 2)

In [14]:
df.isnull().sum() #means column 1 has 0 null values
#first thing you check in any data set

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [15]:
df["Column1"].value_counts()

Column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [17]:
`df[["Column1", "Column2"]] #calling the columns

SyntaxError: invalid syntax (2886607523.py, line 1)